---
abstract: 'Push Mojolicious logs to Google Chrome console'
author:
  - 'Viktor Turskyi <koorchik@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131490'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ChromeLogger
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.0
  perl: 5.01
version: 0.03
